### PR TITLE
Comic Neue files ready to go onboard

### PR DESCRIPTION
**Pull request by vv-monsalve**
It includes new OTF and Webfont files

### CODE REVIEW

**Comment by crozynski** [comment]
Hi Viviana,
Hope you've had a good, flu-free, weekend :)

– I've done a detailed comparison of the previous CN with yours. It's a far better product now and I'm very happy with it.

– For DESCRIPTION.en._us.html, I will remove the line: "It's perfect as a display face, for marking up comments, and writing office memos." before merging.

– I've updated the booklet to use your font files, renamed the Obliques to Italics in the booklet, and updated my repo.

– If it's possible to rename the Angular Oblique font files to Angular Italic I would be very grateful, but understand if that's out of scope. It may cause some confusion.

– I'll mark this release as v2.5. Are you happy for me to credit you in any release notes?

– If you're interested in being commissioned to update the Angular version too, please email me a quote to do that.

Could you please confirm those points before I merge. Thanks!

**Comment by vv-monsalve** [comment]
> – I've done a detailed comparison of the previous CN with yours. It's a far better product now and I'm very happy with it.

Really glad to hear this.

> – For DESCRIPTION.en._us.html, I will remove the line: "It's perfect as a display face, for marking up comments, and writing office memos." before merging.

Ok, so I'll probably need to stop the merging and Pull that change because that caused a conflict now with the PR.

> – I've updated the booklet to use your font files, renamed the Obliques to Italics in the booklet, and updated my repo.

Now I've seen it! It looks good! Nevertheless, I've noticed that some paragraphs still have some kerning adjustments in some words that are no longer needed after spacing and kerning improvements. So please try the paragraph keeping both tracking and kerning without any modification to better test the font.

> – If it's possible to rename the Angular Oblique font files to Angular Italic I would be very grateful, but understand if that's out of scope. It may cause some confusion.

I could do it by opening the original files, rename them and export them again with just that change for now.

> – I'll mark this release as v2.5. Are you happy for me to credit you in any release notes?

Ok, so the current version is 2.003 I would suggest avoiding huge leaps on versions number, it could be left as 2.005 or even 2.1 if you want to mark a milestone. Let me know what you think and I'll change it in the file.
Thanks for credit me as a collaborator, I appreciate it.

> – If you're interested in being commissioned to update the Angular version too, please email me a quote to do that.

I would be interested in working on Angular variant. However, for the sake of the process, I would propose to finish on the Rounded process first and get it published ;-)

> Could you please confirm those points before I merge. Thanks!

I should stop this PR, pull your last changes and reopen it after that, to solve the conflict in the current PR.

**Comment by crozynski** [comment]
> > – I've updated the booklet to use your font files, renamed the Obliques to Italics in the booklet, and updated my repo.
> 
> Now I've seen it! It looks good! Nevertheless, I've noticed that some paragraphs still have some kerning adjustments in some words that are no longer needed after spacing and kerning improvements. So please try the paragraph keeping both tracking and kerning without any modification to better test the font.
> 
> > > Okay thank you, I will update this post merge.
>
> > – If it's possible to rename the Angular Oblique font files to Angular Italic I would be very grateful, but understand if that's out of scope. It may cause some confusion.
> 
> I could do it by opening the original files, rename them and export them again with just that change for now.
> 
> > > Yes please. Appreciate it.
>
> > – I'll mark this release as v2.5. Are you happy for me to credit you in any release notes?
> 
> Ok, so the current version is 2.003 I would suggest avoiding huge leaps on versions number, it could be left as 2.005 or even 2.1 if you want to mark a milestone. Let me know what you think and I'll change it in the file.
>
> > > I was seeing v2.4 here: https://github.com/crozynski/comicneue/releases 
> > > Is the versioning in the font files out of sync with Github's? 
> 
> Thanks for credit me as a collaborator, I appreciate it.
> 
> > > I will update the booklet and site and let you know when it's done so you can check :)
> 
> > – If you're interested in being commissioned to update the Angular version too, please email me a quote to do that.
> 
> I would be interested in working on Angular variant. However, for the sake of the process, I would propose to finish on the Rounded process first and get it published ;-)
> 
> > > Great! I hope I can afford you :)
>

**Comment by vv-monsalve** [comment]
> I was seeing v2.4 here: https://github.com/crozynski/comicneue/releases
> Is the versioning in the font files out of sync with Github's?

Unless we are talking about something different. The version number on the file of that release is 2.003. So in that case, I guess yes, the version on the file is out of sync with Github.
Screen Shot 2020-03-11 at 10 41 32

**Comment by crozynski** [comment]
Yes it looks like they're out of sync. It's not ideal but not that important imo. Let's get this PR merged. 2.003 is fine. Thanks :)

**Comment by vv-monsalve** [comment]
Good! Please let me know when you merge it so I can continue the process.

**Pull request merged**
